# Generated by Django 4.1.12 on 2023-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('range', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('upper', models.CharField(max_length=11)),
                ('lower', models.CharField(max_length=12)),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'frequencies',
            },
        ),
    ]
